### ISSUE TITLE
unique threshold across units

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/thinkhazard_processing#27]
In [thinkhazard_processing.yaml](https://github.com/GFDRR/thinkhazard_processing/blob/master/thinkhazard_processing.yaml), thresholds are currently specific to a raster unit.
They should not be IMO.

Instead, we should be able to internally convert from one unit to another (eg: 1m = 100 cm).
This way, there will be a unique threshold value per (hazard_type, local/global).

**Comment by pgiraud** [comment]
Also related to https://github.com/GFDRR/thinkhazard/issues/374

**Comment by fvanderbiest** [comment]
Discussing this with @NicolasT-brgm ...

We agreed to say that:
- 1g  = 9.80665 m/s² = 980.665 cm/s² = 980.665 gal
- PGA-g and SA-g share the unit (g), not their thresholds
- Files with SA-g unit should not be retained by the THOR tool
- PGA-gal seems to be compatible with PGA-g but with a normalizing ratio in between, given the fact that 1 gal = 1 cm/s²

SA stands for "spectral acceleration", see http://earthquake.usgs.gov/hazards/about/technical.php#sa

MMI stands for "Modified Mercalli Intensity" see https://en.wikipedia.org/wiki/Mercalli_intensity_scale

**Comment by fvanderbiest** [comment]
In addition, unit validation should take place during harvesting step, not during processing step.
As a result, this [code](https://github.com/GFDRR/thinkhazard_processing/blob/94b53809d079e24d6224963fbf949dff95d87568/thinkhazard_processing/harvesting.py#L161-L164) should also validate units.

**Comment by fvanderbiest** [comment]
To date, on GeoNode, datasets advertise these units:
- drought : WCI
- earthquake: PGA-g, PGA-gal, SA-g, MMI
- coastal flood : m, cm
- river flood : cm, dm, m
- strong wind : km/h

Should the tool be able to handle other units ?
Should the thresholds differ when the data unit changes (eg for EQ)? Or should we apply a "normalizing ratio" to convert from one unit to an other one, for which the threshold is set ?

**Comment by fvanderbiest** [comment]
Updated today:
- earthquake: PGA-g, PGA-g-per, PGA-gal, SA-g, MMI

**Comment by fvanderbiest** [comment]
@stufraser1 confirms that 1 PGA-g = 980.665 PGA-gal

100 PGA-g-percent = 1 PGA-g-decimal = 1 PGA-g

g and g-dec shouldn't both be used. I suggested amending the label 'g' to 'g-decimal' in Geonode only to distinguish it from g-percent 

PGA can be defined as:
- a proportion of gravitational force as a decimal: e.g. 1, or 0.74 g
- a proportion of gravitational force as a percent: e.g. 100, or 74 %g

or
- a unit of acceleration in 'old units': 980.665, or 725.69 gal which is equal to a unit of acceleration in SI units: 980.665, or 725.69 cm/s^2 

An earthquake can cause acceleration > 1 g, so decimal can for example exceed 1.5g, or 150 %g

**Comment by fvanderbiest** [comment]
Document where the thresholds for each hazard type can be found: https://docs.google.com/document/d/1fdbKi3OmqKIAslq7_N9tlo_JadsK6WF59Cwju71MnFM/edit#

**Comment by fvanderbiest** [comment]
OK, leaving this as a "nice to have" improvement for now, after discussion with @pgiraud
